# This role is kinda wild in that you can run it against either a server or a site.
- name: get the ansible_env on nosudo to find the user's home dir
  setup:
    filter: ansible_env
  when: "'nosudo' in group_names"

- name: Set the backup user
  ansible.builtin.set_fact:
    backup_user: "{{ username if 'nosudo' in group_names else 'root' }}"

- name: Set the ssh key location
  ansible.builtin.set_fact:
    ssh_key_location: "{{ ansible_env.HOME + '/include/megaphone/ssh' if 'mayfirst_ng_site' in group_names else ( ansible_env.HOME + '/.ssh' if 'nosudo' in group_names else '/root/.ssh') }}"

- name: Set the repo name - with sudo (server-level)
  ansible.builtin.set_fact:
    reponame: "{{ client }}-{{ hostname }}"
    passphrase: "{{ lookup('community.general.passwordstore', client + '/' + hostname + '/borg/remote create=true length=32') }}"
  when: "'nosudo' not in group_names and 'mayfirst_ng_site' not in group_names"

- name: Set the repo name(s) - with no sudo (site-level)
  ansible.builtin.set_fact:
    reponame: "{{ client }}-{{ hostname }}-{{ bare_url }}"
    passphrase: "{{ lookup('community.general.passwordstore', client + '/' + hostname + '/' + bare_url + '/borg/remote create=true length=32') }}"
  when: "'nosudo' in group_names or 'mayfirst_ng_site' in group_names"

- name: create a keypair for backup user
  user:
    name: "{{ backup_user }}"
    generate_ssh_key: yes
    ssh_key_file: "{{ ssh_key_location + '/id_ed25519' }}"
    ssh_key_type: ed25519

- name: get the public key
  command: "cat {{ ssh_key_location }}/id_ed25519.pub"
  register: publickey
  changed_when: false

# If your public key isn't on the rsync.net account this will fail!
- name: get the authorized_keys from rsync.net
  local_action: command ssh {{ rsyncnet_user }}@{{ rsyncnet_server }} cat .ssh/authorized_keys
  register: installed_keys
  become: no
  changed_when: false

- name: Add the public key to the local authorized_keys file
  shell: echo {{ publickey.stdout }} | ssh {{ rsyncnet_user }}@{{ rsyncnet_server }} 'dd of=.ssh/authorized_keys oflag=append conv=notrunc'
  delegate_to: 127.0.0.1
  become: no
  when: publickey.stdout not in installed_keys.stdout_lines

- name: Add the rsync.net public hostkey to known_hosts
  known_hosts:
    key: "{{ rsyncnet_public_hostkey }}"
    name: "{{ rsyncnet_server }}"
    path: "{{ ssh_key_location + '/known_hosts' }}"
  become: "{{ 'no' if ('nosudo' in group_names or 'mayfirst_ng_site' in group_names) else 'yes' }}"

- name: Check if the remote repo exists
  command: ssh  -o UserKnownHostsFile={{ ssh_key_location + '/known_hosts' }} -i {{ ssh_key_location + '/id_ed25519' }} {{ rsyncnet_user }}@{{ rsyncnet_server }} ls -l "{{ reponame + '/config' }}"
  register: remoterepo
  changed_when: false
  failed_when: false

  # FIXME: Once Debian 10 ships and we have borgbackup 1.1+ on all systems, change the encryption to blake2b.
- name: Create a borg repo on rsync.net
  command: "borg init {{ rsyncnet_user }}@{{ rsyncnet_server }}:{{ reponame }} -e repokey --remote-path=borg12"
  environment:
    BORG_PASSPHRASE: "{{ passphrase }}"
  delegate_to: 127.0.0.1
  become: no
  when: remoterepo.rc == 1

